server {
    listen 8080;
    root /usr/share/nginx/html;

    location /api/ {
        proxy_pass http://backend:8081;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri /index.html;
    }
}
